apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-hello-world.fullname" . }}
  labels:
    {{- include "node-hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "node-hello-world.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "node-hello-world.name" . }}
    spec:
      containers:
      - name: node-hello-world
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
