apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-hello-world.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "node-hello-world.name" . }}
