apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-hello-world.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ include "node-hello-world.name" . }}
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
