apiVersion: v1
kind: Service
metadata:
  name: node-hello-world-service
spec:
  type: NodePort
  selector:
    app: node-hello-world
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
